<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="wall" params="
      prefix
      parent
      width
      dir
      mount_xyz
      mount_rpy
      color"
  >

    <!-- Constants -->
    <xacro:property name="flip" value="${dir}" />

    <xacro:property name="x_size" value="${width}" />
    <xacro:property name="y_size" value="0.025" />
    <xacro:property name="z_size" value="2.5" />

    <xacro:property name="x_origin" value="-${x_size / 2}" />
    <xacro:property name="y_origin" value="${dir * y_size / 2}" />
    <xacro:property name="z_origin" value="${z_size / 2}" />

    <link name="${prefix}base_link" >
      <visual>
        <geometry>
          <box size="${x_size} ${y_size} ${z_size}" />
        </geometry>
        <origin xyz="${x_origin} ${y_origin} ${z_origin}" rpy="0.0 0.0 0.0" />
        <material name="${color}" />
      </visual>
      <collision>
        <geometry>
          <box size="${x_size} ${y_size} ${z_size}" />
        </geometry>
        <origin xyz="${x_origin} ${y_origin} ${z_origin}" rpy="0.0 0.0 0.0" />
      </collision>
    </link>

    <joint name="${parent}_to_${prefix}base_link" type="fixed" >
      <parent link="${parent}" />
      <child link="${prefix}base_link" />
      <origin xyz="${mount_xyz}" rpy="${mount_rpy}" />
    </joint>
    
  </xacro:macro>

</robot>