verbose: true
base_link: base_link
models:
  - name: arm            
    type: chain
    frame: ur5_wrist_3_link
  - name: camera
    type: camera3d        
    frame: camera_color_optical_frame  
    topic: /camera/depth/color/points 
free_params:
  - ur5_shoulder_pan_joint
  - ur5_shoulder_lift_joint
  - ur5_elbow_joint
  - ur5_wrist_1_joint
  - ur5_wrist_2_joint
  - ur5_wrist_3_joint
free_frames:
  - name: camera_color_joint
    x: true
    y: true
    z: true
    roll: true
    pitch: true
    yaw: true
  - name: checkerboard
    x: true
    y: true
    z: true
    roll: true
    pitch: true
    yaw: true
free_frames_initial_values:
 - name: checkerboard
   x: 0.150384
   y: -0.125692
   z: -0.0177028
   roll: -3.13496
   pitch: 0.000590985
   yaw: -3.13496
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: camera
   model_b: arm
 - name: restrict_camera
   type: outrageous
   param: camera_color_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
