verbose: true
base_link: tractor_base
models:
  - name: manipulator            
    type: chain
    frame: wrist_3_link
  - name: camera
    type: camera3d        
    frame: camera_color_frame  
    topic: /camera/depth/color/points 
free_params:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
free_frames:
  - name: camera_color_joint
    x: true
    y: true
    z: true
    roll: true
    pitch: true
    yaw: true
  - name: checkerboard
    x: true
    y: false
    z: true
    roll: false
    pitch: true
    yaw: false
# free_frames_initial_values:
#  - name: checkerboard
#    x: 0.0918467
#    y: -0.802267
#    z: 0.73784
#    roll: -1.74677
#    pitch: 1.40228
#    yaw: 2.65126
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: camera
   model_b: manipulator
 - name: restrict_camera
   type: outrageous
   param: camera_color_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
