verbose: true
base_link: tractor_base
models:
  - name: arm            
    type: chain
    frame: wrist_3_link
  - name: camera
    type: camera3d        
    frame: camera_depth_optical_frame  
    topic: /camera/depth/color/points 
free_frames:
  - name: checkerboard
    x: true
    y: true
    z: true
    roll: true
    pitch: true
    yaw: true
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: camera
   model_b: arm
 - name: restrict_camera
   type: outrageous
   param: camera_color_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
