chains:
  - name: manipulator 
    topic: /move_group/display_planned_path
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    planning_group: manipulator   
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /camera/depth/color/points
    camera_info_topic: /camera/depth/camera_info
    camera_sensor_name: camera 
    chain_sensor_name: manipulator    
    points_x: 6
    points_y: 4
    square_size: 0.035